sudo: required
language: bash
dist: trusty

services:
  - docker

branches:
  except:
    - /^pr\..*/
    - /^features\..*/
  only:
    - master
    - develop

# before install any component
before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

before_script:
  - env | sort
  - IMAGE_NAME=clamav-server
  - IMAGE_BASE="${ACCOUNT_ID:-djantaio}/${IMAGE_NAME}"
  - IMAGE_TAG="${IMAGE_BASE}"
  - IMAGE_BRANCH="${IMAGE_BASE}:${TRAVIS_BRANCH}"

  # Making sure we login ...
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

after_script:
  - docker images
  - docker ps -a

before_deploy:
 - docker tag "$IMAGE_TAG" "$IMAGE_BRANCH"

after_success:
  # Only continue for 'develop' or 'release/*' branches
  - if [ "$TRAVIS_BRANCH" =~ "^(develop$|feature//*)" ]; then
    docker --debug build -t "$IMAGE_TAG" .
    docker push "${IMAGE_BRANCH}";
    fi

deploy:
  provider: script
  script: docker push "$IMAGE_BRANCH"
#  on:
#    branch: develop

#notifications:
#  email: false
#  slack:
#    rooms:
#    on_success: always
#    on_failure: always
#    template:
#    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
#      by %{author} %{result} in %{duration}
#  webhooks:
#    urls:
#    on_success: change
#    on_failure: always
#    on_start: never
