sudo: required
language: bash
dist: trusty

services:
  - docker

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
  #    - /^[0-9]/

  # safelist
  only:
  - master
  - develop
  - release
  - /^[0-9]/

# before install any component
before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

before_script:
  - env | sort
  - IMAGE_NAME=clamav-server
  - IMAGE_BASE="${ACCOUNT_ID:-djantaio}/${IMAGE_NAME}"
  - IMAGE_TAG="${IMAGE_BASE}"
  - IMAGE_BRANCH="${IMAGE_BASE}:${TRAVIS_BRANCH}"

  # Making sure we login ...
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin

after_script:
  - docker images
  - docker ps -a

# Expected stage definition
stages:
  - name: develop
    if: (branch = develop AND type != pull_request) AND commit_message !~ /^(prepare release ([0-9\.]+))$/
  - name: snapshot
    if: branch = master AND type != pull_request AND commit_message !~ /^(prepare release ([0-9\.]+))$/
  - name: release
#    if: ((tag =~ /^[0-9\.]+$/ OR $TRAVIS_TAG =~ /^[0-9\.]+$/) OR $TRAVIS_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/ OR $TRAVIS_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/)
    if: tag =~ /^[0-9\.]+$/

# Build job configuration
jobs:
  include:
  - stage: develop
    name: "Build and Unit Testing the develop & PR branch"
    install: true
    before_deploy:
      - docker tag "$IMAGE_TAG" "$IMAGE_BRANCH"
    script:
      - docker --debug build -t "$IMAGE_TAG" .
    deploy:
      provider: script
      script: docker push "$IMAGE_BRANCH"
      on:
        branch: develop

  - stage: snapshot
    name: "Deploy Snapshot to Maven repo"
    install: true
    script:
    - echo "Not Yet Implemented ..."

  - stage: release
    name: "Release the latest tag to docker registry"
    install: true
    script:
    - echo "Not Yet Implemented ..."

#after_success:
#  # Only continue for 'develop' or 'release/*' branches
#  - if [ "$TRAVIS_BRANCH" =~ "^(develop$|feature//*)" ]; then
#    docker --debug build -t "$IMAGE_TAG" .
#    docker push "${IMAGE_BRANCH}";
#    fi

#notifications:
#  email: false
#  slack:
#    rooms:
#    on_success: always
#    on_failure: always
#    template:
#    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch}
#      by %{author} %{result} in %{duration}
#  webhooks:
#    urls:
#    on_success: change
#    on_failure: always
#    on_start: never
