language: bash

services:
  - docker

branches:
  except:
    - /^pr\..*/
    - /^features\..*/
  only:
      - master
      - develop

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine

  - docker build -t djantaio/djantaio-docker-clamav .
  #- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  #- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      echo "...success..."
      #docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      #docker push USER/REPO;
    fi

notifications:
  slack:
    secure: LFNWwOhrauoI8phLvFkKnAFkXEfIKxgzSVvONtqYX8fkECikQLGkWMe2K8VaCKgW7KdDJgKvhr/I3wkd5G29iOAExb/1lOqyqLJ35VDg7BJzYNNmbDKZ/VkFkWbKpHF2az80RZQRssJcyB4X9HqLcOlg+3BRss92Ojj52UQCPQs/pixdoI4eLxB6FdSfT+/D3PDLktTt1fnDi7R0DORyRVxg3IGdEslDo6ccHrjxA40KNbJhC6XKjP1Rt3qCPgGf+/gnPnQiCex5IAVoqiA4TjQU4du6rpzmKE5qtDyuCyETOWA0pG2oUgSmVt6A6yg0pGGpZFyACSLvvh869qg6s27QyRDS8zjbGsRD1Z7ks32wNfAVwkOGnLUrzODipWtHsdS3SczrBCHFelo+aV2hSvkLGUX/k+ZPpbOpruLtPznh4UEZcF8hYhnaMEdO7VMXSYwSaD08Grcf/uvF3apKQknKA3YbPYfSRZdexG8s4jaHnAx/tMkMXyxSBAAnMGG99y7ACdQ+BSTHPMUqSCtxS6Daw90Zt1TJxYsYRtTXx4GaYZJgFELFPfw9GTsot1U9tsvuG5UBC9jwkSm4pltTz2Ag1p0koYgb5j4WZKlvEqWRE6O2fmswo0lVKVzYNnjom4x09TN0J55JRZgIGDQGEYVl+Yfw+TUv5fWU45GMHsI=
    rooms:
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#docker
      - djantaio:1GeeSv1noSekK9to1yTqsbDw#general
    on_success: always # default: always
    on_failure: always # default: always
    on_pull_requests: false
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
